@@ -0,0 +1,29 @@
# Create a new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "test@test.local",
  "name": "Keks",
  "password": "123456"
}

###

# Get user by ID
GET http://localhost:3000/api/auth/fe72128c-03d7-4752-a46a-c70eb965dbd2 HTTP/1.1

###

# Login user by email and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "test@test.local",
  "password": "123456"
}

###

# Change user's password
POST http://localhost:3000/api/auth/fe72128c-03d7-4752-a46a-c70eb965dbd2/change-password HTTP/1.1
Content-Type: application/json

{
  "password": "1234567"
}

###